version: '3.8'
services:
  store-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: store-api
    restart: always
    ports:
      - 3000:3000
    networks:
      - default
    depends_on:
      - store-db
    env_file:
      - .env

  store-db:
    container_name: store-db
    image: postgres:13
    restart: always
    ports:
      - 5432:5432
    networks:
      - default
    env_file:
      - .env
    volumes:
      - store-db:/var/lib/postgresql/data

  store-front:
    container_name: store-front
    build:
      context: .
      dockerfile: Dockerfile.front
    restart: always
    ports:
      - 4200:80
    env_file:
      - .env

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - store-db
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin:/var/lib/pgadmin
    restart: always
      
volumes:
  store-db:
    name: store-db
  pgadmin:
    name: pgadmin

networks:
  default:
