FROM node:17.3.0 AS deps
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

FROM node:17.3.0 AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

COPY prisma ./prisma/

RUN npx prisma generate
RUN npm run build:frontend

FROM nginx:1.19.2

WORKDIR /usr/share/nginx/html

COPY --from=builder /app/dist/apps/frontend ./
COPY --from=builder /app/apps/frontend/nginx-docker.conf /etc/nginx/nginx.conf